const CURRENCY_NAMES_SHORT_AND_LONG = {
    "AUD": "Australischer Dollar (A$)",
    "BGN": "Bulgarischer Lew (лв)",
    "BRL": "Brasilianischer Real (R$)",
    "CAD": "Kanadischer Dollar (C$)",
    "CHF": "Schweizer Franken (CHF)",
    "CNY": "Renminbi Yuan (¥)",
    "CZK": "Tschechische Krone (Kč)",
    "DKK": "Dänische Krone (kr)",
    "GBP": "Britisches Pfund (£)",
    "HKD": "Hongkong-Dollar (HK$)",
    "HUF": "Ungarischer Forint (Ft)",
    "IDR": "Indonesische Rupiah (Rp)",
    "ILS": "Israelischer Neuer Schekel (₪)",
    "INR": "Indische Rupie (₹)",
    "ISK": "Isländische Krone (kr)",
    "JPY": "Japanischer Yen (¥)",
    "KRW": "Südkoreanischer Won (₩)",
    "MXN": "Mexikanischer Peso (MX$)",
    "MYR": "Malaysischer Ringgit (RM)",
    "NOK": "Norwegische Krone (kr)",
    "NZD": "Neuseeländischer Dollar (NZ$)",
    "PHP": "Philippinischer Peso (₱)",
    "PLN": "Polnischer Złoty (zł)",
    "RON": "Rumänischer Leu (lei)",
    "SEK": "Schwedische Krone (kr)",
    "SGD": "Singapur-Dollar (S$)",
    "THB": "Thailändischer Baht (฿)",
    "TRY": "Türkische Lira (₺)",
    "USD": "US-Dollar ($)",
    "ZAR": "Südafrikanischer Rand (R)",
    "EUR": "Euro (€)"
}
